// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_API.Data;

#nullable disable

namespace Proyecto_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240410172600_AlimentarTabla")]
    partial class AlimentarTabla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyecto_API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Prueba1",
                            Correo = "cortesantonio822@gmail.com",
                            FechaCreacion = new DateTime(2024, 4, 10, 11, 25, 59, 952, DateTimeKind.Local).AddTicks(2180),
                            ImagenUrl = "",
                            Nombre = "Prueba",
                            Numero = "4494597406"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Prueba2",
                            Correo = "cortesantonio820@gmail.com",
                            FechaCreacion = new DateTime(2024, 4, 10, 11, 25, 59, 952, DateTimeKind.Local).AddTicks(2191),
                            ImagenUrl = "",
                            Nombre = "Prueba2",
                            Numero = "4494597405"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
